#
# sleet_and_restart example
#
# This Makefile is the simplest solution to use
# processing.make. It contains a oneliner that includes
# the processing.make script to build, run, export etc.
#
# To get the help page run:
#    $ make help
#
#
# This file is part of the processing.make project.
#


include ../../../processing.make
