#
# Add the template extension to our Makefile.
#
#
# This file is part of the processing_makefile project
# version 0.1.0
#

BASE_DIR=../../../
include $(BASE_DIR)processing.make

# include the extension
include $(BASE_DIR)processing.make.extensions/template.make
