#
# example3_custom
#
# This file is part of the processing.make project.
#

# Custom export directory
EXPORT_FOLDERNAME = distribution

# Custom MacOSX export folder
EXPORT_MACOSX_FOLDERNAME = mac


include ../../../processing.make
