#
# doxygen example.
#
#
# This file is part of the processing.make project.
#

BASE_DIR=../../../
include $(BASE_DIR)processing.make

# include the extension
include $(BASE_DIR)processing.make.extensions/doxygen.make
