#
# example3_custom
#
# This file is part of the processing_makefile project
#

# Custom export directory
EXPORT_FOLDERNAME = distribution

# Custom MacOSX export folder
EXPORT_MACOSX_FOLDERNAME = mac


# Custom windows export folder
EXPORT_WINDOWS_FOLDERNAME = win

# Custom Linux (32-, 64-bit) export folder
EXPORT_LINUX32_FOLDERNAME = linux32bit
EXPORT_LINUX64_FOLDERNAME = linux

include ../../../processing.make
