#
# custom_path example
#
# If you want to run (or build, export etc.) a sketch
# at an other directory you can use the
# "SKETCH_DIRECTORY" parameter to set the path.
#
#
# This file is part of the processing.make project.
#


# The $(PWD) get the path of this Makefile. From this
# directory you can navigate to your sketch.
# This implementation is used as default parameter at the
# processing.make if no "SKETCH_DIRECTORY" parameter exist.
SKETCH_DIRECTORY = $(PWD)/path/to/your/processing/sketch

# You can also set the sketchpath hardcoded like this:
#SKETCH_DIRECTORY = /Users/your_name/path/to/your/processing/sketch


include ../../../processing.make
